databases:
  - name: django-cruddb
    plan: free
    databaseName: djangocrud
    user: root

services:
  - type: web
    plan: free
    name: django-crud
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn django-crud.asgi:application -k uvicorn.workers.UvicornWorker"    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-cruddb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4